### ISSUE TITLE
Faraday::BadRequestError: [!] the server responded with status 400

### ISSUE THREAD

**Issue by vasilybodnarchuk** [fastlane/fastlane-plugin-firebase_app_distribution#147]
**Lane**:
```
    lane :beta_firebase_deliver do |options|
        firebase_app_distribution(
                                  app: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
                                  groups: 'internal-ios',
                                  release_notes_file: './fastlane/meta/release_notes.txt',
                                  ipa_path: options[:ipa_path]
                                  )
    end
```

**Command**: `
bundle exec fastlane beta_firebase_deliver ipa_path:./fastlane/temp/app.ipa`

**Console**:
```
10:01:05]: ------------------------------
[10:01:05]: --- Step: default_platform ---
[10:01:05]: ------------------------------
[10:01:05]: Driving the lane 'ios beta_firebase_deliver' 🚀
[10:01:05]: -----------------------------------------------------------
[10:01:05]: --- Step: fastlane add_plugin firebase_app_distribution ---
[10:01:05]: -----------------------------------------------------------
[10:01:05]: $ fastlane add_plugin firebase_app_distribution
[10:01:06]: ▸ +------------------------+---------+------------------------+
[10:01:06]: ▸ |                       Used plugins                        |
[10:01:06]: ▸ +------------------------+---------+------------------------+
[10:01:06]: ▸ | Plugin                 | Version | Action                 |
[10:01:06]: ▸ +------------------------+---------+------------------------+
[10:01:06]: ▸ | fastlane-plugin-fireb  | 0.2.0   | firebase_app_distribu  |
[10:01:06]: ▸ | ase_app_distribution   |         | tion_login             |
[10:01:06]: ▸ |                        |         | firebase_app_distribu  |
[10:01:06]: ▸ |                        |         | tion                   |
[10:01:06]: ▸ +------------------------+---------+------------------------+
[10:01:07]: ▸ [10:01:07]: Make sure to commit your Gemfile, Gemfile.lock and Pluginfile to version control
[10:01:07]: ▸ Installing plugin dependencies...
[10:01:07]: ▸ Successfully installed plugins
[10:01:07]: -----------------------------
[10:01:07]: --- Step: update_fastlane ---
[10:01:07]: -----------------------------
[10:01:07]: Looking for updates for fastlane...
[10:01:07]: It seems that your Gem directory is not writable by your current user.
[10:01:07]: fastlane would need sudo rights to update itself, however, running 'sudo fastlane' is not recommended.
[10:01:07]: If you still want to use this action, please read the documentation on how to set this up:
[10:01:07]: https://docs.fastlane.tools/actions/update_fastlane/
[10:01:07]: -------------------------------------
[10:01:07]: --- Step: fastlane update_plugins ---
[10:01:07]: -------------------------------------
[10:01:07]: $ fastlane update_plugins
[10:01:08]: ▸ +------------------------+---------+------------------------+
[10:01:08]: ▸ |                       Used plugins                        |
[10:01:08]: ▸ +------------------------+---------+------------------------+
[10:01:08]: ▸ | Plugin                 | Version | Action                 |
[10:01:08]: ▸ +------------------------+---------+------------------------+
[10:01:08]: ▸ | fastlane-plugin-fireb  | 0.2.0   | firebase_app_distribu  |
[10:01:08]: ▸ | ase_app_distribution   |         | tion_login             |
[10:01:08]: ▸ |                        |         | firebase_app_distribu  |
[10:01:08]: ▸ |                        |         | tion                   |
[10:01:08]: ▸ +------------------------+---------+------------------------+
[10:01:11]: ▸ Successfully updated plugins
[10:01:11]: ---------------------------------------
[10:01:11]: --- Step: firebase_app_distribution ---
[10:01:11]: ---------------------------------------
[10:01:11]: No authentication method specified. Using cached Firebase CLI credentials.
[10:01:11]: 🔐 Authenticated successfully.
[10:01:12]: ✅ This IPA has been uploaded before. Skipping upload step.
+------------------+---------------------------+
|                 Lane Context                 |
+------------------+---------------------------+
| DEFAULT_PLATFORM | ios                       |
| PLATFORM_NAME    | ios                       |
| LANE_NAME        | ios beta_firebase_deliver |
+------------------+---------------------------+
[10:01:13]: the server responded with status 400

+------+-----------------------------------------------+-------------+
|                          fastlane summary                          |
+------+-----------------------------------------------+-------------+
| Step | Action                                        | Time (in s) |
+------+-----------------------------------------------+-------------+
| 1    | default_platform                              | 0           |
| 2    | fastlane add_plugin firebase_app_distribution | 1           |
| 3    | update_fastlane                               | 0           |
| 4    | fastlane update_plugins                       | 4           |
| 💥   | firebase_app_distribution                     | 2           |
+------+-----------------------------------------------+-------------+

[10:01:13]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Distribute to hockeyapp suddenly failing
    https://github.com/fastlane/fastlane/issues/400 [closed] 8 💬
    22 Sep 2016

➡️  Deliver: Segmentation fault after completing
    https://github.com/fastlane/fastlane/issues/10479 [closed] 16 💬
    10 May 2018

➡️  Uploading assets with a GitHub release fails in `set_github_release`
    https://github.com/fastlane/fastlane/issues/9922 [closed] 5 💬
    18 Nov 2017

and 1 more at: https://github.com/fastlane/fastlane/search?q=the%20server%20responded%20with%20status%20400&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
Faraday::BadRequestError: [!] the server responded with status 400
  /Library/Ruby/Gems/2.6.0/gems/faraday-1.0.1/lib/faraday/response/raise_error.rb:16:in `on_complete'
  /Library/Ruby/Gems/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:12:in `block in call'
  /Library/Ruby/Gems/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:65:in `on_complete'
  /Library/Ruby/Gems/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
  /Library/Ruby/Gems/2.6.0/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
  /Library/Ruby/Gems/2.6.0/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
  /Library/Ruby/Gems/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
  /Library/Ruby/Gems/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:279:in `post'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.2.0/lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb:68:in `post_notes'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.2.0/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:46:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:109:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /Library/Ruby/Gems/2.6.0/gems/fastlane-2.159.0/bin/fastlane:23:in `<top (required)>'
  /usr/local/bin/fastlane:23:in `load'
  /usr/local/bin/fastlane:23:in `<top (required)>'
```

**Comment by vasilybodnarchuk** [comment]
Hm... problem was with long `./fastlane/meta/release_notes.txt`

**Comment by elvisun** [comment]
Same problem here but my release note is only 226 char long...
