### ISSUE TITLE
The server responded with status 400

### ISSUE THREAD

**Issue by dummyco** [fastlane/fastlane-plugin-firebase_app_distribution#159]
Hello!
We've started getting 400 errors right after 0.2.2 update:

```
[20:07:57]: ---------------------------------------
[20:07:57]: --- Step: firebase_app_distribution ---
[20:07:57]: ---------------------------------------
[20:07:57]: Authenticating with GOOGLE_APPLICATION_CREDENTIALS environment variable: /home/circleci/google-service-account.json
[20:07:57]: 🔐 Authenticated successfully.
[20:07:57]: ⌛ Uploading the APK.
[20:08:03]: ✅ Uploaded the APK.
+------------------+---------+
|        Lane Context        |
+------------------+---------+
| DEFAULT_PLATFORM | android |
| PLATFORM_NAME    |         |
| LANE_NAME        | beta    |
+------------------+---------+
[20:08:03]: the server responded with status 400

+------+----------------------------+-------------+
|                fastlane summary                 |
+------+----------------------------+-------------+
| Step | Action                     | Time (in s) |
+------+----------------------------+-------------+
| 1    | opt_out_usage              | 0           |
| 2    | Verifying fastlane version | 0           |
| 3    | default_platform           | 0           |
| 💥   | firebase_app_distribution  | 6           |
+------+----------------------------+-------------+

[20:08:03]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Distribute to hockeyapp suddenly failing
    https://github.com/fastlane/fastlane/issues/400 [closed] 8 💬
    22 Sep 2016

➡️  Uploading assets with a GitHub release fails in `set_github_release`
    https://github.com/fastlane/fastlane/issues/9922 [closed] 5 💬
    18 Nov 2017

➡️  Deliver: Segmentation fault after completing
    https://github.com/fastlane/fastlane/issues/10479 [closed] 16 💬
    10 May 2018

and 1 more at: https://github.com/fastlane/fastlane/search?q=the%20server%20responded%20with%20status%20400&type=Issues&utf8=✓

bundler: failed to load command: fastlane (/home/circleci/.rubies/ruby-2.6.1/bin/fastlane)
Faraday::BadRequestError: [!] the server responded with status 400
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/response/raise_error.rb:16:in `on_complete'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:12:in `block in call'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:65:in `on_complete'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:279:in `post'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.2.2/lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb:68:in `post_notes'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.2.2/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:37:in `run'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:10:in `block in parsing_binding'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/fastlane-2.161.0/bin/fastlane:23:in `<top (required)>'
  /home/circleci/.rubies/ruby-2.6.1/bin/fastlane:23:in `load'
  /home/circleci/.rubies/ruby-2.6.1/bin/fastlane:23:in `<top (required)>'

```
```
+-------------------------------------------+---------+---------------------------------+
|                                     Used plugins                                      |
+-------------------------------------------+---------+---------------------------------+
| Plugin                                    | Version | Action                          |
+-------------------------------------------+---------+---------------------------------+
| fastlane-plugin-firebase_app_distribution | 0.2.2   | firebase_app_distribution       |
|                                           |         | firebase_app_distribution_login |
+-------------------------------------------+---------+---------------------------------+

```

Any ideas on these? I'll provide additional information if necessary.

**Comment by jongwonatwork** [comment]
I have the same problem.

**Comment by denstepa** [comment]
same here, problem appeared after upgrading from 2.159.0 to 2.161.0.
Downgrading back seems to help

**Comment by joshdholtz** [comment]
Looking into the issue! Will hopefully have a solution soon.

**Comment by brownoxford** [comment]
Fastlane is now setting default content type of `application/x-www-form-urlencoded` on all requests that do not specify a content-type header value. See discussion [here](https://github.com/fastlane/fastlane/issues/17339#issuecomment-700805500)

**Comment by joshdholtz** [comment]
Yup yup! I’m working on a fix for exactly that 😊

**Comment by joshdholtz** [comment]
Fixed in https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/pull/160 by @brownoxford ❤️  I will comment when the new gem is out.

**Comment by lfkellogg** [comment]
The fix is now available in plugin [v0.2.3](https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/releases/tag/v0.2.3).

**Comment by SerhiiMatvieiev** [comment]
How to downgrade fastlane 2.161.0 to 2.160.0 ?

**Comment by joshdholtz** [comment]
@SerhiiMatvieiev No need to downgrade anymore! You can upgrade the firebase plugin to `0.2.3` (that has the fix in it)

**Comment by brownoxford** [comment]
> How to downgrade fastlane from 2.161.0 to 2.160.0 ?

As @joshdholtz mentioned, you don't need to do this anymore. That said, downgrading is pretty simple:

1. Update your `Gemfile` to specify a version for the fastlane gem
```
gem "fastlane", "= 2.160.0"
```
2. Run `bundle install`

**Comment by artyomdevyatov** [comment]
For anyone who suffers from this error and found this page:
If changing gem versions didn't help, pay attention to release notes you are attaching. Firebase have limit of 16384 symbols. If your release notes has more, firebase will return exactly same error (400) without any additional information about the limit. I've faced this issue at the same time the original issue with 0.2.2 version happened. So it was not obvious what was the problem and leaded me in the wrong direction.
Hope it helps!

**Comment by tagboola** [comment]
@artyomdevyatov good catch! We'll look into adding better error messaging.

**Comment by tagboola** [comment]
Hey @artyomdevyatov with [v0.2.4](https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/releases/tag/v.0.2.4) we now show a less generic error message when release notes are too long 🙂
