### ISSUE TITLE
[!] the server responded with status 400

### ISSUE THREAD

**Issue by SBNTT** [fastlane/fastlane-plugin-firebase_app_distribution#164]
using 

- `fastlane-plugin-firebase` `0.2.3`

- `fastlane` `2.162.0` 

lane definition:
```
lane :deploy_beta do
    firebase_app_distribution(
      app: "________",
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
      service_credentials_file: "../firebase-app-distribution-key.json",
    )
  end
```

outputs:
```
[✔] 🚀 
+---------------------------+---------+---------------------------+
|                          Used plugins                           |
+---------------------------+---------+---------------------------+
| Plugin                    | Version | Action                    |
+---------------------------+---------+---------------------------+
| fastlane-plugin-firebase  | 0.2.3   | firebase_app_distributio  |
| _app_distribution         |         | n_login                   |
|                           |         | firebase_app_distributio  |
|                           |         | n                         |
+---------------------------+---------+---------------------------+

[15:55:17]: ------------------------------
[15:55:17]: --- Step: default_platform ---
[15:55:17]: ------------------------------
[15:55:17]: Driving the lane 'android deploy_beta' 🚀
[15:55:17]: ---------------------------------------
[15:55:17]: --- Step: firebase_app_distribution ---
[15:55:17]: ---------------------------------------
[15:55:17]: Authenticating with --service_credentials_file path parameter: ../firebase-app-distribution-key.json
[15:55:19]: 🔐 Authenticated successfully.
+------------------+---------------------+
|              Lane Context              |
+------------------+---------------------+
| DEFAULT_PLATFORM | android             |
| PLATFORM_NAME    | android             |
| LANE_NAME        | android deploy_beta |
+------------------+---------------------+
[15:55:19]: the server responded with status 400

+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | default_platform          | 0           |
| 💥   | firebase_app_distributio  | 1           |
|      | n                         |             |
+------+---------------------------+-------------+

[15:55:19]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Distribute to hockeyapp suddenly failing
    https://github.com/fastlane/fastlane/issues/400 [closed] 8 💬
    22 Sep 2016

➡️  [regression] firebase_app_distribution action is broken in 2.161.0
    https://github.com/fastlane/fastlane/issues/17339 [closed] 32 💬
    29 minutes ago

➡️  Uploading assets with a GitHub release fails in `set_github_release`
    https://github.com/fastlane/fastlane/issues/9922 [closed] 5 💬
    18 Nov 2017

and 2 more at: https://github.com/fastlane/fastlane/search?q=the%20server%20responded%20with%20status%20400&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane ([...]/vendor/bundle/ruby/2.6.0/bin/fastlane)
Faraday::BadRequestError: [!] the server responded with status 400
  [...]/vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/response/raise_error.rb:16:in `on_complete'
  [...]/vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:12:in `block in call'
  [...]/vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:65:in `on_complete'
  [...]/vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
  [...]/vendor/bundle/ruby/2.6.0/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
  [...]/vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
  [...]/vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
  [...]/vendor/bundle/ruby/2.6.0/gems/faraday-1.0.1/lib/faraday/connection.rb:198:in `get'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.2.3/lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb:97:in `get_upload_token'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.2.3/lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb:143:in `upload'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.2.3/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:31:in `run'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:6:in `block (2 levels) in parsing_binding'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  [...]/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  [...]/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  [...]/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-2.162.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  [...]/vendor/bundle/ruby/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-2.162.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  [...]/vendor/bundle/ruby/2.6.0/gems/fastlane-2.162.0/bin/fastlane:23:in `<top (required)>'
  [...]/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `load'
  [...]/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
```

ios deployment fails the same way

**Comment by SBNTT** [comment]
I just realized that i've used the firebase `Project ID` instead of `App ID`....
