### ISSUE TITLE
Posting release notes returns 400

### ISSUE THREAD

**Issue by Furman950** [fastlane/fastlane-plugin-firebase_app_distribution#165]
This seems like it's related to this [issue](https://github.com/fastlane/fastlane/issues/17339) 

Here is what I'm getting from the logs
```
/home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-1.0.1/lib/faraday/response/raise_error.rb:16:in `on_complete': [!] the server responded with status 400 (Faraday::BadRequestError)
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-1.0.1/lib/faraday/response.rb:12:in `block in call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-1.0.1/lib/faraday/response.rb:65:in `on_complete'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-1.0.1/lib/faraday/response.rb:11:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday_middleware-1.0.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in `build_response'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in `run_request'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/faraday-1.0.1/lib/faraday/connection.rb:279:in `post'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-plugin-firebase_app_distribution-0.2.3/lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb:69:in `post_notes'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-plugin-firebase_app_distribution-0.2.3/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:37:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.162.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.162.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:146:in `block (2 levels) in parsing_binding'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.162.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.162.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.162.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.162.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.162.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.162.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.162.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.162.0/bin/fastlane:23:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/fastlane:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

Here are the versions

Fastlane: `2.162.0`
```
+---------------------------------------------+---------+---------------------------------+
|                                      Used plugins                                       |
+---------------------------------------------+---------+---------------------------------+
| Plugin                                      | Version | Action                          |
+---------------------------------------------+---------+---------------------------------+

| fastlane-plugin-commit_android_version_bump | 0.2.0   | commit_android_version_bump     |
| fastlane-plugin-android_versioning          | 0.5.3   | get_version_code                |
|                                             |         | increment_version_name          |
|                                             |         | get_value_from_build            |
|                                             |         | set_value_in_build              |
|                                             |         | get_version_name                |
|                                             |         | increment_version_code          |
| fastlane-plugin-firebase_app_distribution   | 0.2.3   | firebase_app_distribution_login |
|                                             |         | firebase_app_distribution       |
+---------------------------------------------+---------+---------------------------------+
```

Here is how I'm calling the firebase_app_distribution from the Fastfile
```
    firebase_app_distribution(
      app: "my_app_id...",
      groups: "group1,group2",
      release_notes_file: "fastlane/changelog.txt"
    )  
```

And I was able to get it to build by calling the firebase_app_distribution and setting the `release_notes` to an empty string like this

```
    firebase_app_distribution(
      app: "my_app_id...",
      groups: "group1,group2",
      release_notes: ""
    )  
```

**Comment by tagboola** [comment]
@Furman950 how long are the release notes in `fastlane/changelog.txt`? I think this may be related to [artyomdevyatov's comment in issue #159](https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/issues/159#issuecomment-703039141). We have a 16384 character limit on release notes.

We'll look into adding a better error messaging.

**Comment by Furman950** [comment]
@tagboola Yeah your right, my change log has more that the character limit... Thanks!

**Comment by tagboola** [comment]
Hey @Furman950 with [v0.2.4](https://github.com/fastlane/fastlane-plugin-firebase_app_distribution/releases/tag/v.0.2.4) we now show a less generic error message when release notes are too long 🙂
