### ISSUE TITLE
bad URI(is not URI?):

### ISSUE THREAD

**Issue by crewshin** [fastlane/fastlane-plugin-firebase_app_distribution#218]
### *** Steps to file a bug ***
There are no steps really. I'm just trying to use firebase_app_distribution indicated below. I will also mention that this is being run on gitlab ci.

### Issue Description
```
[07:35:01]: bad URI(is not URI?): "/v1alpha/apps/1:204.....0894:ios:553e6......7683f\n?appView=BASIC" <-- 💥

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | opt_out_usage                                                 | 0           |
| 2    | default_platform                                              | 0           |
| 3    | Switch to ios get_config lane                                 | 0           |
| 4    | pwd                                                           | 0           |
| 5    | curl -o ....zip 'https://dev....                              | 5           |
| 6    | unzip -o ....zip 'ios/*'                                      | 0           |
| 7    | Switch to ios build_archive lane                              | 0           |
| 8    | Switch to ios update_signing lane                             | 0           |
| 9    | app_store_connect_api_key                                     | 0           |
| 10   | match                                                         | 3           |
| 11   | update_code_signing_settings                                  | 0           |
| 12   | build_app                                                     | 211         |
| 13   | defaults read /Users/jenkins/builds/i5RPyg1z/0/...            | 0           |
| 💥   | firebase_app_distribution                                     | 0           |
+------+---------------------------------------------------------------+-------------+
[07:35:01]: fastlane finished with errors
Looking for related GitHub issues on fastlane/fastlane...
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
#######################################################################
# fastlane 2.191.0 is available. You are on 2.190.0.
# You should use the latest version.
# Please update using `bundle update fastlane`.
#######################################################################
2.191.0 Improvements
* [produce][spaceship] add ability to fetch and display available bundle capabilities (#19168) via Shyam Lad
* [supply] fix upload_mapping for multiple mapping_paths (#19211) via Steffen Rusitschka
* [spaceship] add requests to remove or replace visible apps (#19200) via Lukasz Grabowski
* [regression][zip] fix the `shellescape` for the folder path (#19207) via Manish Rathi
* [deliver] introduce a new synchronization logic for screenshots (#19070) via Satoshi Namai
Please update using `bundle update fastlane`
bundler: failed to load command: fastlane (/Users/jenkins/.rbenv/versions/2.7.4/bin/fastlane)
URI::InvalidURIError: [!] bad URI(is not URI?): "/v1alpha/apps/1:204......0894:ios:553e6.......7683f\n?appView=BASIC"
  /Users/jenkins/.rbenv/versions/2.7.4/lib/ruby/2.7.0/uri/rfc3986_parser.rb:67:in `split'
  /Users/jenkins/.rbenv/versions/2.7.4/lib/ruby/2.7.0/uri/rfc3986_parser.rb:73:in `parse'
  /Users/jenkins/.rbenv/versions/2.7.4/lib/ruby/2.7.0/uri/common.rb:234:in `parse'
  /Users/jenkins/.rbenv/versions/2.7.4/lib/ruby/2.7.0/uri/common.rb:737:in `URI'
  /Users/jenkins/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/faraday-1.6.0/lib/faraday/utils.rb:67:in call
```
##### Configuration
```
lane :publish_to_firebase do |options|
		get_config(options) <-- this just fetches some xcconfig files. Works fine.
		build_archive(options) <-- works fine.

		plist_path = File.expand_path("../Application/GoogleService-Info.plist", Dir.pwd) <-- both of these work fine.
		GOOGLE_APP_ID = sh("""defaults read #{plist_path} GOOGLE_APP_ID""")

		firebase_app_distribution( <-- 💥
			app: GOOGLE_APP_ID,
			groups: ENV["FIREBASE_DISTRO_GROUPS"],
			ipa_path: Actions.lane_context[SharedValues::IPA_OUTPUT_PATH],
			release_notes: ENV["FIREBASE_RELEASE_NOTES"], <-- empty for now. All the rest of these are fine.
			service_credentials_file: ENV["FIREBASE_SERVICE_CREDENTIALS_FILE"]
		)

		clean
	end
```
##### Complete verbose output
Naa... too much private data to be confident I didn't miss something.

##### Environment
| Library     | Version |
| ----------- | ----------- |
| fastlane | [2.190.0] |
| fastlane-plugin-firebase_app_distribution | [0.2.9] |

**Comment by tagboola** [comment]
Ahh it looks there is a new line character in your app ID

/v1alpha/apps/1:204.....0894:ios:553e6......7683f**\n**?appView=BASIC

This can happen when you copy and paste the app ID from the Firebase Console. If you remove the new line character it _should_ work.

**Comment by crewshin** [comment]
Woa... nice catch! However it wasn't a copy paste error. It was actually the `defaults read #{plist_path} GOOGLE_APP_ID` that was adding the new line. Adding `.chomp("")` to the end fixed it.

Btw, the only way to really see if it existed or not was to add another (inner) pair of quotes to the log: `puts "'#{GOOGLE_APP_ID}'"`

Thanks for the help!
