### ISSUE TITLE
Uploading build to firebase fails:  [!] the server responded with status 500 (Faraday::ServerError) 

### ISSUE THREAD

**Issue by tim-nguyen** [fastlane/fastlane-plugin-firebase_app_distribution#248]
### Issue Description
Uploading build to firebase fails:  [!] the server responded with status 500 (Faraday::ServerError) 

##### Complete verbose output
```
bundler: failed to load command: fastlane (/home/circleci/circleci/vendor/bundle/ruby/2.6.0/bin/fastlane)
Traceback (most recent call last):
	50: from /home/circleci/.rubies/ruby-2.6.1/bin/bundle:23:in `<main>'
	49: from /home/circleci/.rubies/ruby-2.6.1/bin/bundle:23:in `load'
	48: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/exe/bundle:37:in `<top (required)>'
	47: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	46: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/exe/bundle:49:in `block in <top (required)>'
	45: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/cli.rb:25:in `start'
	44: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	43: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/cli.rb:31:in `dispatch'
	42: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	41: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	40: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	39: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/cli.rb:477:in `exec'
	38: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/cli/exec.rb:23:in `run'
	37: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/cli/exec.rb:58:in `kernel_load'
	36: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/cli/exec.rb:58:in `load'
	35: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
	34: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `load'
	33: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/bin/fastlane:23:in `<top (required)>'
	32: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	31: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	30: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	29: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	28: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	27: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	26: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	25: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	24: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	23: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	22: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	21: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	20: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	19: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	18: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	17: from Fastfile:57:in `block (2 levels) in parsing_binding'
	16: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	15: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	14: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	13: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	12: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	11: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	10: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 9: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.3.1/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:37:in `run'
	 8: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.3.1/lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb:93:in `get_aab_info'
	 7: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/faraday-1.7.1/lib/faraday/connection.rb:200:in `get'
	 6: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/faraday-1.7.1/lib/faraday/connection.rb:511:in `run_request'
	 5: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/faraday-1.7.1/lib/faraday/rack_builder.rb:154:in `build_response'
	 4: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/faraday_middleware-1.1.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
	 3: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/faraday-1.7.1/lib/faraday/middleware.rb:18:in `call'
	 2: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/faraday-1.7.1/lib/faraday/response.rb:59:in `on_complete'
	 1: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/faraday-1.7.1/lib/faraday/middleware.rb:19:in `block in call'
/home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/faraday-1.7.1/lib/faraday/response/raise_error.rb:34:in `on_complete': the server responded with status 500 (Faraday::ServerError)
	50: from /home/circleci/.rubies/ruby-2.6.1/bin/bundle:23:in `<main>'
	49: from /home/circleci/.rubies/ruby-2.6.1/bin/bundle:23:in `load'
	48: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/exe/bundle:37:in `<top (required)>'
	47: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
	46: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/exe/bundle:49:in `block in <top (required)>'
	45: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/cli.rb:25:in `start'
	44: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	43: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/cli.rb:31:in `dispatch'
	42: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	41: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	40: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	39: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/cli.rb:477:in `exec'
	38: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/cli/exec.rb:23:in `run'
	37: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/cli/exec.rb:58:in `kernel_load'
	36: from /home/circleci/.rubies/ruby-2.6.1/lib/ruby/gems/2.6.0/gems/bundler-2.2.26/lib/bundler/cli/exec.rb:58:in `load'
	35: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `<top (required)>'
	34: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/bin/fastlane:23:in `load'
	33: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/bin/fastlane:23:in `<top (required)>'
	32: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
	31: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	30: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
	29: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	28: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
	27: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	26: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	25: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	24: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
	23: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	22: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	21: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	20: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	19: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	18: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	17: from Fastfile:57:in `block (2 levels) in parsing_binding'
	16: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	15: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	14: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	13: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	12: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	11: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	10: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-2.193.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	 9: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.3.1/lib/fastlane/plugin/firebase_app_distribution/actions/firebase_app_distribution_action.rb:37:in `run'
	 8: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/fastlane-plugin-firebase_app_distribution-0.3.1/lib/fastlane/plugin/firebase_app_distribution/client/firebase_app_distribution_api_client.rb:93:in `get_aab_info'
	 7: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/faraday-1.7.1/lib/faraday/connection.rb:200:in `get'
	 6: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/faraday-1.7.1/lib/faraday/connection.rb:511:in `run_request'
	 5: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/faraday-1.7.1/lib/faraday/rack_builder.rb:154:in `build_response'
	 4: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/faraday_middleware-1.1.0/lib/faraday_middleware/response_middleware.rb:36:in `call'
	 3: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/faraday-1.7.1/lib/faraday/middleware.rb:18:in `call'
	 2: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/faraday-1.7.1/lib/faraday/response.rb:59:in `on_complete'
	 1: from /home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/faraday-1.7.1/lib/faraday/middleware.rb:19:in `block in call'
/home/circleci/circleci/vendor/bundle/ruby/2.6.0/gems/faraday-1.7.1/lib/faraday/response/raise_error.rb:34:in `on_complete': [!] the server responded with status 500 (Faraday::ServerError)

Exited with code exit status 1
```

##### Environment

| Library     | Version |
| ----------- | ----------- |
| fastlane | [2.192.0] |
| fastlane-plugin-firebase_app_distribution | [0.3.1] |

**Comment by mario-bolanos-fivestars** [comment]
Same here!

**Comment by sebargarcia** [comment]
Same here, we have configured Fastlane to uploads AAB to firebase app distribution, and when Fastlane tries to make a request to  GET endpoint to get AABInfo it fails with error 500. With APKs everything is working, 
But this was working a few days ago and then suddenly start to fails with this error.

**Comment by tagboola** [comment]
Hey folks! Tunde from the App Distribution team here. We're currently taking a look into this. Thank you for your patience!

**Comment by tagboola** [comment]
@tim-nguyen or any other folks seeing this issue do you mind printing your verbose output by setting `debug` parameter of the  `firebase_app_distribution` action to` true`. Note: The verbose output may contain sensitive information, so please check the output and replace anything sensitive before posting.

**Comment by mario-bolanos-fivestars** [comment]
Oh yeah we did that and we got this
![image](https://user-images.githubusercontent.com/85318958/131727909-d1abb2fe-f7e8-4622-8465-e2b393a48ae3.png)

**Comment by mario-bolanos-fivestars** [comment]
Oh yeah we did that and we got the following verbose @tagboola 

![Screen Shot 2021-09-01 at 2 00 43 PM](https://user-images.githubusercontent.com/85318958/131728878-acd5ec79-8163-46f1-a2c8-5c0b7c22d73c.png)

**Comment by sebargarcia** [comment]
> 
> 
> Oh yeah we did that and we got this @tagboola
> 
> ![image](https://user-images.githubusercontent.com/85318958/131727909-d1abb2fe-f7e8-4622-8465-e2b393a48ae3.png)

Yes that the error, it authenticates and then when make the request to get aab info it fails..

**Comment by sebargarcia** [comment]
> 
> 
> Oh yeah we did that and we got the following verbose @tagboola
> 
> ![Screen Shot 2021-09-01 at 2 00 43 PM](https://user-images.githubusercontent.com/85318958/131728878-acd5ec79-8163-46f1-a2c8-5c0b7c22d73c.png)

Yeah, that´s the exact same error. It tries to get AAB info and fails.

**Comment by tagboola** [comment]
@mario-bolanos-fivestars and/or @sebargarcia can you try to upload again?

**Comment by tim-nguyen** [comment]
@tagboola , it's working for me now

**Comment by kurdybacha** [comment]
It is failing for me with the same issue (0.3.1). Any update on this?

**Comment by mario-bolanos-fivestars** [comment]
@tagboola It keeps failing

**Comment by tagboola** [comment]
Hey folks. Thanks for your patience. We're still looking into this, but If you're looking to get unblocked please downgrade to version `0.2.9`.

It would be super helpful if we can get some more information to help debug. Would any of you be interested in joining http://firebase-community.slack.com? If so drop a message in the #app-distribution room and I can shoot you a DM to get some more information.

**Comment by tagboola** [comment]
Hey folks we submitted a fix for the issue we think you're running into. When you have chance can you try uploading an AAB with version `0.3.1` again?

**Comment by tagboola** [comment]
@kurdybacha thanks for confirming and sorry again for the inconvenience! Going to close this for now feel free to re-open if anyone runs into the issue again.
